// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA36It8tCqHvGYMnO1imXUa61FCTBmOImg',
    appId: '1:99099315567:web:6e4a8d6f852b0f8156ac9a',
    messagingSenderId: '99099315567',
    projectId: 'mobile-hobbytrack',
    authDomain: 'mobile-hobbytrack.firebaseapp.com',
    storageBucket: 'mobile-hobbytrack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCShmyUkRygHWPX6EqTIE6rKnjB9cOoWo8',
    appId: '1:99099315567:android:e9dd7b770ad6c51556ac9a',
    messagingSenderId: '99099315567',
    projectId: 'mobile-hobbytrack',
    storageBucket: 'mobile-hobbytrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEoritxZenzU1aHWxWySOMvGUlXwg95wE',
    appId: '1:99099315567:ios:9179ba255d87073456ac9a',
    messagingSenderId: '99099315567',
    projectId: 'mobile-hobbytrack',
    storageBucket: 'mobile-hobbytrack.firebasestorage.app',
    iosBundleId: 'com.example.hobbytrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEoritxZenzU1aHWxWySOMvGUlXwg95wE',
    appId: '1:99099315567:ios:9179ba255d87073456ac9a',
    messagingSenderId: '99099315567',
    projectId: 'mobile-hobbytrack',
    storageBucket: 'mobile-hobbytrack.firebasestorage.app',
    iosBundleId: 'com.example.hobbytrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA36It8tCqHvGYMnO1imXUa61FCTBmOImg',
    appId: '1:99099315567:web:e81915261073f5eb56ac9a',
    messagingSenderId: '99099315567',
    projectId: 'mobile-hobbytrack',
    authDomain: 'mobile-hobbytrack.firebaseapp.com',
    storageBucket: 'mobile-hobbytrack.firebasestorage.app',
  );
}
